version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: orakgaraki-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_PROD}
      MYSQL_DATABASE: ${DB_NAME_PROD}
      MYSQL_USER: ${DB_USERNAME_PROD}
      MYSQL_PASSWORD: ${DB_PASSWORD_PROD}
    ports:
      - "${DB_PORT_PROD:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD_PROD}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # Redis
  redis:
    image: redis:7-alpine
    container_name: orakgaraki-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orakgaraki-app
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - ./logs:/var/log/orak
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - DB_HOST=${DB_HOST_PROD:-orakgaraki-mysql}
      - DB_PORT=3306
      - DB_NAME=${DB_NAME_PROD}
      - DB_USERNAME=${DB_USERNAME_PROD}
      - DB_PASSWORD=${DB_PASSWORD_PROD}
      - REDIS_HOST=orakgaraki-redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - orakgaraki-network

volumes:
  mysql_data:
  redis_data:

networks:
  orakgaraki-network:
    driver: bridge
